service: fooweiguo-aws-python-http-api-project
frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.9

functions:
  hello:
    handler: handler.hello
    events:
      - httpApi:
          path: /
          method: get
  myapi:
    handler: myapi.newapi
    events:
      - httpApi:
          path: /newapi
          method: get
